version: "3.8"

services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  jaflow-postgres:
    image: postgres:15
    container_name: jaflow-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/

  jaflow-keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: jaflow-keycloak
    command: start-dev --import-realm
    environment:
      # Configuration Proxy (essentiel pour Nginx)
      KC_PROXY: edge                 # Indique que Keycloak est derrière un reverse proxy
      KC_HTTP_ENABLED: 'true'        # Active HTTP (nécessaire car Nginx gère le port)
      KC_HOSTNAME_STRICT: 'false'    # Moins strict pour le nom d'hôte en développement (utile pour localhost)
      KC_HOSTNAME_STRICT_HTTPS: 'false' # Pas de HTTPS strict ici
      # KC_HOSTNAME: localhost         # Le nom d'hôte public (sans le port car géré par le proxy/headers)
      KC_HTTP_RELATIVE_PATH: /keycloak # Définit le chemin de base pour Keycloak (IMPORTANT pour correspondre à la config Nginx)

      # Identifiants Admin Keycloak (à la première connexion)
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Configuration Base de données
      KC_DB: postgres
      KC_DB_URL_HOST: jaflow-postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
     - ./docker/keycloak/realms:/opt/keycloak/data/import
    depends_on:
      - jaflow-postgres

  jaflow-sb-container:
    container_name: jaflow-sb-container
    build:
      context: ./springboot-container
      dockerfile: Dockerfile
    volumes:
      - ./docker/local-volumes/springboot-jars:/app/springboot-jars
    ports:
      - "8081:8081"
      - "9082:8082"
      - "9083:8083"
      - "6005:5005"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - jaflow-keycloak

  jaflow-nginx:
    image: nginx:latest
    container_name: jaflow-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/pages/:/usr/share/nginx/html
    depends_on:
      - jaflow-sb-container

volumes:
  portainer_data:
  postgres-db-data:

