version: '3.8'

services:

  jaflow-nginx:
    image: nginx:latest
    container_name: jaflow-nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - jaflow-net


  jaflow-postgres:
    image: postgres:15
    container_name: jaflow-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/
    networks:
      - jaflow-net

  jaflow-keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: jaflow-keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: jaflow-postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./docker/keycloak/realms:/opt/keycloak/data/import
    depends_on:
      - jaflow-keycloak
    networks:
      - jaflow-net

  jaflow-sb-container:
    build:
      context: ./springboot-container
      dockerfile: Dockerfile
    volumes:
      - ./docker/local-volumes/springboot-jars:/app/springboot-jars
    ports:
      - "8081:8081"         # Port Spring Boot
      - "8082:8082"         # Port Spring Boot
      - "8083:8083"         # Port Spring Boot
      - "5005:5005"         # Debug remote (optionnel)
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - jaflow-net
    depends_on:
      - jaflow-postgres

volumes:
  postgres-db-data:

networks:
  jaflow-net:
